-- **************************************** CURSOR FOR AIRPORT MANAGEMENT SYSTEM ***********************************
-- SELECT QUERY USED FOR CURSOR -----------------------
SELECT DISTINCT TK.TICKET_NUMBER, TK.PASSPORTNO,PS.PNAME, PS.AGE, TK.SOURCE,TK.DESTINATION, TK.DATE_OF_BOOKING,TK.DATE_OF_TRAVEL,TK.SEATNO,TK.CLASS, TKE.PRICE, PS.GEN, TK.DATE_OF_CANCELLATION, TK.BOOKING_STATUS, TKE.REFUND FROM TICKET1 AS TK, PASSENGER AS PS, TICKET2 AS TKE WHERE TK.PASSPORTNO = PS.PASSPORTNO AND TK.DATE_OF_BOOKING = TKE.DATE_OF_BOOKING;

--  CURSOR TRAVERSAL THROUGH DATA IN MULTIPLE TABLES

DELIMITER $$
CREATE PROCEDURE LIST_PASS_DETAILS22 ()
BEGIN
DECLARE FLAG INT DEFAULT 0;
DECLARE TKNUM, TKPASSNUM, PSNAME, PSAGE, TKSOUR, TKDEST, TKDOBKNG, TKDOT, TKSEAT, TKCLASS, TKPRICE, PSGEN, TKDOC, BOOKING_STATUS, REFUND VARCHAR(20);
DECLARE PASS_CURSOR22 CURSOR FOR
SELECT DISTINCT TK.TICKET_NUMBER, TK.PASSPORTNO,PS.PNAME, PS.AGE, TK.SOURCE,TK.DESTINATION, TK.DATE_OF_BOOKING,TK.DATE_OF_TRAVEL,TK.SEATNO,TK.CLASS, TKE.PRICE, PS.GEN, TK.DATE_OF_CANCELLATION, TK.BOOKING_STATUS, TKE.REFUND FROM TICKET1 AS TK, PASSENGER AS PS, TICKET2 AS TKE WHERE TK.PASSPORTNO = PS.PASSPORTNO AND TK.DATE_OF_BOOKING = TKE.DATE_OF_BOOKING;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET FLAG = 1;
OPEN PASS_CURSOR22;
GET1_NAME: LOOP
FETCH PASS_CURSOR22 INTO TKNUM, TKPASSNUM, PSNAME, PSAGE, TKSOUR, TKDEST, TKDOBKNG, TKDOT, TKSEAT, TKCLASS, TKPRICE, PSGEN, TKDOC, BOOKING_STATUS, REFUND;
IF FLAG = 1 THEN
LEAVE GET1_NAME;
END IF;
INSERT INTO PASSENGER_DATA VALUES(TKNUM, TKPASSNUM, PSNAME, PSAGE, TKSOUR, TKDEST, TKDOBKNG, TKDOT, TKSEAT, TKCLASS, TKPRICE, PSGEN, TKDOC, BOOKING_STATUS, REFUND);
END LOOP GET1_NAME;
CLOSE PASS_CURSOR22;
END$$
DELIMITER ;

-- TO CALL CURSOR --

CALL tempAMS.LIST_PASS_DETAILS22();
SELECT DISTINCT * FROM PASSENGER_DATA;

-- CREATING PROCEDURE TO CALL CURSOR ----
DELIMITER &&  
CREATE PROCEDURE TO_GET_DTA12 ()  
BEGIN
    TRUNCATE TABLE PASSENGER_DATA;  
    CALL tempAMS.LIST_PASS_DETAILS22();
    SELECT DISTINCT TKNUM AS `TICKET NO.`, TKPASSNUM AS `PASSPORT NO.`, PSNAME AS `PASSENGER NAME`, PSAGE AS `AGE`, TKSOUR AS `SOURCE`, TKDEST AS `DEST`, TKDOBKNG AS `Date of Booking`, TKDOT AS `Date of Travel`, TKSEAT AS `SEAT NO.`, TKCLASS AS `CLASS`, TKPRICE AS `PRICE`, PSGEN AS `GEN`, TKDOC AS `Date of Cancel`, BOOKING_STATUS, REFUND FROM PASSENGER_DATA ORDER BY TKNUM;
END &&  
DELIMITER ;

-- TO CALL PROCEDURE ----- 
CALL TO_GET_DTA12();