SHOW TRIGGERS;
DROP TRIGGER before_insert_empworkinghours;

-- *************************** TRIGGERS FOR AIRPORT MANAGEMENT SYSTEM ***************************

-- TRIGGER 1 TO CHECK THE MINIMUM AGE OF PASSENGER IF ALONE THEN UPDATE WITH GUARDIAN CHARGE

DELIMITER //  
Create Trigger TICKET_GUARDIAN_CHRGE  
BEFORE INSERT ON PASSENGER_DATA FOR EACH ROW  
BEGIN
IF  
NEW.PSAGE <= 10 THEN SET NEW.TKPRICE = NEW.TKPRICE + 6000;  
END IF;   
END //
DELIMITER;

-- TRIGGER 2 TO CHARGE 25% OF AMOUNT TO PASSENGER IF TICKET IS CANCELLED

BOOKING_STATUS
DELIMITER //  
Create Trigger REFUND_GENERATOR  
BEFORE INSERT ON PASSENGER_DATA FOR EACH ROW  
BEGIN
IF  
NEW.BOOKING_STATUS = 'BOOKING CANCELLED' THEN SET NEW.REFUND = NEW.TKPRICE - NEW.TKPRICE * 25 / 100;
END IF;   
END //
DELIMITER;

 -- TRIGGER 3 TO UPDATE MAIN TABLE AND SUB TABLE IF TICKET IS CANCELLED

DELIMITER &&  
Create Trigger  CANCELLATION_DATA_UPDATE
AFTER INSERT ON TICKET3 FOR EACH ROW  
BEGIN

UPDATE PASSENGER_DATA
INNER JOIN TICKET3 ON PASSENGER_DATA.TKPASSNUM = TICKET3.PASSPORTNO
SET PASSENGER_DATA.TKDOC = TICKET3.DATE_OF_CANCELLATION,
	PASSENGER_DATA.BOOKING_STATUS = TICKET3.BOOKING_STATUS
WHERE TICKET3.PASSPORTNO = PASSENGER_DATA.TKPASSNUM;

UPDATE TICKET1
INNER JOIN TICKET3 ON TICKET1.PASSPORTNO = TICKET1.PASSPORTNO
SET TICKET1.DATE_OF_CANCELLATION = TICKET3.DATE_OF_CANCELLATION,
    TICKET1.BOOKING_STATUS = TICKET3.BOOKING_STATUS
WHERE TICKET3.PASSPORTNO = TICKET1.PASSPORTNO;
END;   
END && 
DELIMITER ;